# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding   = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

[env.prod]
name = "pick-a-bots-2025"
routes = [
  { pattern = "pickabots.ramsocunsw.org", custom_domain = true },
  { pattern = "www.pickabots.ramsocunsw.org", custom_domain = true }
]

[env.dev]
name = "pick-a-bots-2025-dev"
routes = [
  { pattern = "pickabots.dev.ramsocunsw.org", custom_domain = true },
  { pattern = "www.pickabots.dev.ramsocunsw.org", custom_domain = true }
]




# ----------------------------
# Optional sections commented out below
# ----------------------------

# # Environment Variables
# [vars]
# MY_VARIABLE = "production_value"

# # Service Bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# # Smart Placement
# # Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# # [placement]
# # mode = "smart"
