# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding   = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

[env.prod]
name = "pick-a-bots-2025"
routes = [
  { pattern = "pickabots.ramsocunsw.org", custom_domain = true },
  { pattern = "www.pickabots.ramsocunsw.org", custom_domain = true }
]

[env.prod.vars]
NEXT_PUBLIC_SUPABASE_URL="https://trvwmuhioifcbeqgskdz.supabase.co"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY="sb_publishable_SHLNdMcONHZv2Fk9Y5AIhA_lGK6By0U"
ACCESS_CODE="PICKABOTS2025"
NEXT_PUBLIC_CHALLONGE_TOURNAMENT_ID="sumobots_2025_dev_mid"
WEBHOOK_SECRET="webhook_secret"

[env.dev]
name = "pick-a-bots-2025-dev"
routes = [
  { pattern = "pickabots.dev.ramsocunsw.org", custom_domain = true },
  { pattern = "www.pickabots.dev.ramsocunsw.org", custom_domain = true }
]

[env.dev.vars]
NEXT_PUBLIC_SUPABASE_URL="https://hgjffdonkkisokreoacp.supabase.co"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY="sb_publishable_qcwz2j4aNb_pBiq45JB5wg_XBJVR7jz"
ACCESS_CODE="PICKABOTS2025"
NEXT_PUBLIC_CHALLONGE_TOURNAMENT_ID="sumobots_2025_dev_mid"
WEBHOOK_SECRET="webhook_secret"


# ----------------------------
# Optional sections commented out below
# ----------------------------

# # Environment Variables
# [vars]
# MY_VARIABLE = "production_value"

# # Service Bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# # Smart Placement
# # Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# # [placement]
# # mode = "smart"
