main = "src/index.ts"
compatibility_date = "2025-06-23"

workers_dev = false

assets = { directory = "public" }

# Production environment
[[env.prod.kv_namespaces]]
binding = "CONFIG_KV"
id = "fa810c3ad25e43cb9f0ead7f87c13205"

[env.prod]
name = "pick-a-bots-2025-cron"
routes = [
  { pattern = "cron.pickabots.ramsocunsw.org", custom_domain = true },
  { pattern = "www.cron.pickabots.ramsocunsw.org", custom_domain = true }
]

[env.prod.triggers]
crons = ["*/1 * * * *"]

# Development environment
[env.dev]
name = "pick-a-bots-2025-cron-dev"
routes = [
  { pattern = "cron.pickabots.dev.ramsocunsw.org", custom_domain = true },
  { pattern = "www.cron.pickabots.dev.ramsocunsw.org", custom_domain = true }
]

[env.dev.triggers]
crons = ["*/5 * * * *"]

[[env.dev.kv_namespaces]]
binding = "CONFIG_KV"
id = "917a9563b08d456ba88aa27a6e81fa61"
